### ISSUE TITLE
Any way to not memorize the rejected promise?

### ISSUE THREAD

**Issue by hossam-fares** [vicanso/promise-memorize#1]
I would like not to memorize the rejected promise, anyway to do it?

Example:

``` js
var memorize = require('promise-memorize');

function promiseFactory() {
  return Q.promise(function (resolve, reject) {
    console.log('Im executing, no cache');
    reject({error: "erro"})
  });
}

var memo = memorize(promiseFactory);
memo(); /// will be rejected and print  'Im executing, no cache'
memo(); // will retrieve the rejection from cache and not execute the promise again
```

**Comment by vicanso** [comment]
No, I don't think so. 
- when `memo` function is called at first time, the `promise` object will be saved in the `Map`.
- when `memo` function is called again,  it will return the first `promise` object, because the result of the first call is not completed(async function).

I suggest you remove the cache when the promise rejects:

``` js
'use strict';
const memorize = require('promise-memorize');
function promiseFactory() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      console.info('Im executing, no cache');
      reject({error: "erro"});
    }, 1);
  });
}
const memo = memorize(promiseFactory, 10);
// first call
memo().catch(err => {
  console.error(err);
  memo.delete();
  memo().catch(err => {
    // not the same sa first call
    console.error(err);
  });
});
memo().catch(err => {
  // the same as first call
  console.error(err);
});
```

**Comment by hossam-fares** [comment]
Thanks for the reply, I will try it that way.

**Comment by hossam-fares** [comment]
working fine with me thanks

**Comment by vicanso** [comment]
@hossam-fares 
I have updated a new version, which supports several events. You can use  the `reject` event to meet the need you mentioned above. There is an [example](https://github.com/vicanso/promise-memorize/blob/master/examples/remove-reject-cache.js).

**Comment by hossam-fares** [comment]
That is very nice, I will try it.
